### ISSUE TITLE
Different results from different KLIFS APIs

### ISSUE THREAD

**Issue by schallerdavid** [volkamerlab/opencadd#105]
Hey @dominiquesydow ,

by accident I bumped into an issue with two available API's of KLIFS. The inconsistency might come from KLIFS, but I thought I'd post it here first before I message Albert.

When using opencadd in version 0.1.1 and version 0.2.0 you get different results:

## Steps to reproduce

- install opencadd in version 0.1.1 and 0.2.0 via conda-forge in different conda environments
- run the following code:

```
from opencadd.databases.klifs import setup_remote
remote = setup_remote()
structures = remote.structures.all_structures()
13896 in structures["structure.klifs_id"].unique()
len(structures)
```
## Expected behavior

- both versions deliver the same results

## Observed behavior

- version 0.1.1 can find "structure.klifs_id" 13896, version 0.2.0 can not
- the "structure.klifs_id" 13896 comes from the PDB code 7n5o, which does not exist at all in version 0.2.0
- version 0.2.0 returns less structures than version 0.1.1

Can you please double check this inconsistency comes from KLIFS?

Thanks,
David

**Comment by dominiquesydow** [comment]
Hi @schallerdavid,

Interesting. 

Just checked the two websites and it seems to be something on the KLIFS site:
https://klifs.net/details.php?structure_id=13896 > returns a structure
https://dev.klifs.net/details.php?structure_id=13896 > returns _no_ structure

**Comment by schallerdavid** [comment]
I did a set comparison of available structure klifs ids. Here are the missing values that are not returned in the new version:

13854, 13855, 13856, 13857, 13858, 13859, 13860, 13861, 13862, 13863, 13864, 13865, 13866, 13867, 13868, 13869, 13870, 13871, 13872, 13873, 13874, 13875, 13876, 13877, 13878, 13879, 13880, 13881, 13882, 13883, 13884, 13885, 13886, 13887, 13888, 13889, 13890, 13891, 13892, 13893, 13894, 13895, 13896, 13897, 13898, 13899, 13900, 13901, 13902, 13903, 13904

Those are actually the highest numbers of structure klifs ids. So it might be that the new API is simply updated a little later?

**Comment by dominiquesydow** [comment]
Oh yes, that seems likely!
