### ISSUE TITLE
Statement of need not found in documentation

### ISSUE THREAD

**Issue by ojeda-e** [volkamerlab/opencadd#124]
Hi @dominiquesydow 

For the current JOSS review, a statement of need should be in both documentation pages and the paper associated with the OpenCADD-KLIFS repository. Currently, I can find the statement of need as a section in this [source](https://github.com/volkamerlab/opencadd/blob/master/papers/opencadd-klifs/paper.md) but not in the provided documentation.

Maybe I am missing it. Would you please share the link where a statement of need in docs is included? 

Thanks.

**Comment by dominiquesydow** [comment]
Hi @ojeda-e,

Thank you for pointing this out; the statement is missing in the documentation.

I suggest adding the "Statement of need" to our docs like this:
https://opencadd.readthedocs.io/en/klifs-stat-of-need/databases_klifs_statement_of_need.html

I copied the paper text, please let me know if this is in compliance with the JOSS requirements for the documentation.

At the moment, the changes are part of PR #125. Happy to merge if you approve of the changes.

**Comment by dominiquesydow** [comment]
Hi @ojeda-e, the statement of need is now in-sync between our documentation and paper. This issue was closed automatically with the PR merges; please re-open if anything is left to update.
