### ISSUE TITLE
Get PDF compiled for JOSS review

### ISSUE THREAD

**Issue by andrewtarzia** [volkamerlab/opencadd#128]
As stated in title - it would be good to read this, rather than the MD file.

Link to JOSS review: openjournals/joss-reviews#3951

**Comment by dominiquesydow** [comment]
Hi @andrewtarzia, 

My apologies for not attending to this earlier. 

We got the compilation running once in the pre-review (see https://github.com/openjournals/joss-reviews/issues/3907#issuecomment-970107477).

I have asked for help to figure out why it is not compiling anymore (see https://github.com/openjournals/joss-reviews/issues/3907#issuecomment-987858595). I will get back to you once the compilation is working again.

**Comment by dominiquesydow** [comment]
The PDF compilation is working now :) See https://github.com/openjournals/joss-reviews/issues/3951#issuecomment-988790990.

**Comment by andrewtarzia** [comment]
Thank you!
