### ISSUE TITLE
An alternative to conda/mamba-based installation

### ISSUE THREAD

**Issue by andrewtarzia** [volkamerlab/opencadd#129]
Are there installation instructions that do not use conda or mamba (e.g. a pip install)?

**Comment by dominiquesydow** [comment]
Hi @andrewtarzia - are you referring to an `opencadd` `pip` package (thus, _not_ the `pip install` we are using [here](https://opencadd.readthedocs.io/en/latest/installing.html#install-from-the-latest-development-snapshot))?

**Comment by andrewtarzia** [comment]
ahh missed that - I will test that install - should be fine! 

Thank you

**Comment by andrewtarzia** [comment]
Worked a charm.
