### ISSUE TITLE
Comments on JOSS manuscript

### ISSUE THREAD

**Issue by andrewtarzia** [volkamerlab/opencadd#133]
Hello. Just read through the manuscript and a few comments:

- [x] Incomplete reference to Raschka on line 46
- [x] The manuscript does not discuss how people would have accessed this data previously. Was the Rest API not accessible through Python already? Therefore, the statement of need is also unclear as it is written (I definitely see the need for the software!).
- [x] The Statement of Need section is too long, the manuscript should have a Description or Use case section.

For https://github.com/openjournals/joss-reviews/issues/3951

**Comment by dominiquesydow** [comment]
@mcs07 and @andrewtarzia thanks a lot for raising these good points! 
My apologies for the delay on my end; I will have drafted an update by tomorrow.

**Comment by dominiquesydow** [comment]
Hi @mcs07 and @andrewtarzia, 

Thanks again for the points you raised in this issue.
Please have a look at the revised version of the manuscript: 
https://github.com/openjournals/joss-reviews/issues/3951#issuecomment-996179098

I have merged your comments with those from @ojeda-e in issue #134 in PR #135.

**Comment by andrewtarzia** [comment]
I am happy with the changes, @dominiquesydow. Thank you! I will write my final comments on the review chain.
