### ISSUE TITLE
Pylint RecursionError

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/opencadd#63]
Since yesterday, I am running into a `pylint` recursion error.

Check out the failed CI: 
https://github.com/volkamerlab/opencadd/runs/1565679662

- `python` 3.8.6
- `pylint` 2.6.0
- `astroid` 2.4.2

The same setup (at least regarding the above mentioned versions) did work 3 days ago:
https://github.com/volkamerlab/opencadd/runs/1552066336

Locally, I can reproduce this error with Python 3.8.6 - `pylint` passes with 3.7.6 though. 

Maybe related:
https://github.com/PyCQA/pylint/issues/2388

Potential next steps:

- [ ] Pin `astroid` to 2.2.5 (see https://github.com/PyCQA/pylint/issues/3982#issuecomment-745236956)
- [dismissed] Pin Python version to 3.7.6 and check if CI passes? Explore higher Python versions?
- [dismissed] Open issue on `pylint` repo? > Many open issues already on this topic.

**Comment by jaimergp** [comment]
There's plenty of opened issues on their repo about that now, so I'd ignore the linting errors for now and proceed normally. I am sure they'll fix it very soon.

**Comment by jaimergp** [comment]
You can pin `astroid` for a quick, temporary solution: https://github.com/PyCQA/pylint/issues/3982#issuecomment-745236956

**Comment by dominiquesydow** [comment]
Interestingly, at the moment it is working again for me, I have no clue why.
Check e.g. this CI run: https://github.com/volkamerlab/opencadd/runs/1572712406

If I encounter the problem again, I will pin `astroid`.

**Comment by jaimergp** [comment]
Some people have mentioned it's a bit stochastic 🤷

**Comment by dominiquesydow** [comment]
Would you therefore pin `astroid` as a precaution?

**Comment by jaimergp** [comment]
It wouldn't hurt! But do leave this open so we remember to unpin it in the future :)

**Comment by tofutofu** [comment]
Just run into this issue also. I get the error 
```
F0002: <class 'RecursionError'>: maximum recursion depth exceeded while calling a Python object (astroid-error)
```
when my source file:
```
from pandas import DataFrame
```
but if I change that to
```
import pandas as pd
```
it doesn't error.

```
python 3.7.9
pylint                    2.6.0            py37hc8dfbb8_1    conda-forge
pytest-pylint             0.18.0             pyhd3deb0d_0    conda-forge
astroid                   2.4.2            py37hc8dfbb8_1    conda-forge
pandas                    1.1.5            py37h010c265_0    conda-forge
```

**Comment by dominiquesydow** [comment]
Closing this issue because I have not encountered it for quite some time (maybe package updates fixed this?).
