### ISSUE TITLE
databases.klifs: HTML-encoded entities in some strings

### ISSUE THREAD

**Issue by jaimergp** [volkamerlab/opencadd#67]
Some fields contain HTML-encoded entities in their values:

![image](https://user-images.githubusercontent.com/2559438/104202419-35ed4080-542b-11eb-9e2a-f50320e02b53.png)

It might be a good idea to [`html.unescape`](https://docs.python.org/3/library/html.html#html.unescape) those. This possibly affects more fields, so it might be a good idea to apply it during the API retrieval in a general way, but I guess you'll know better how to patch this, @dominiquesydow :)

**Comment by dominiquesydow** [comment]
Thanks, @jaimergp, for catching this. Will put it on my list for this week.
