### ISSUE TITLE
Specific OpenCadd package and environment creation link

### ISSUE THREAD

**Issue by Carlbullish** [volkamerlab/opencadd#83]
Hi guy! Great work with the repository. 
I get this error when i try to create the opencadd environment following the install steps i got from here:

https://opencadd.readthedocs.io/en/latest/installing.html

(base) C:\Users\QUE>conda env create -n opencadd -f opencadd/devtools/conda-envs/test_env.yaml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - theseus
  - mmligner
  - muscle

As a learning user though, i get confused on which of the repositories to use in my jupyter notebook and google colab is it 

https://github.com/volkamerlab/opencadd/archive/master.tar.gz 
or 
https://github.com/volkamerlab/opencadd#opencadd

I hope the question doesn't sound too naive :)

**Comment by jaimergp** [comment]
I am afraid these dependencies are only available on Linux and, by the looks of your prompt (`C:\Users`), you are running Windows? I used to work on Windows, but I did have WSL2 (the Ubuntu layer) installed. That should work!

**Comment by dominiquesydow** [comment]
Closing this issue since related to https://github.com/volkamerlab/opencadd/issues/11.
